---
- name: Manage EC2 instances
  hosts: ec2_instances
  become: true
  vars:
    ansible_user: maintuser
    ansible_ssh_private_key_file: /path/to/your/.pem/file
  tasks:
    - name: Create new directory in /opt
      file:
        path: /opt/new_directory
        state: directory
        mode: '0755'

    - name: Download the bin file using wget
      command:
        cmd: wget -O /opt/new_directory/your_bin_file_url
      args:
        creates: /opt/new_directory/your_bin_file

    - name: Execute the bin file
      command: /opt/new_directory/your_bin_file
      args:
        creates: /opt/new_directory/your_bin_file_output_indicator

